<script src="https://cdn.tailwindcss.com"></script>
<!-- Jquery CDN -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js" integrity="sha512-n/4gHW3atM3QqRcbCn6ewmpxcLAHGaDjpEBu4xZd47N0W2oQ+6q7oc3PXstrJYXcbNU1OHdQ1T7pAP+gi5Yu8g==" crossorigin="anonymous"></script>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
<?php
header('X-Frame-Options: GOFORIT');
?>
<div class="w-screen capitalize h-screen flex flex-col justify-center items-center">
    <div class="w-1/2">
        <form action="/admin/products" method="post" class="w-full flex items-center justify-center">
            <input type="text" class="grow px-3 py-2 text-gray-700 hover:shadow-lg hover:ring-2 hover:ring-offset-2 border-gray-300 hover:ring-indigo-300 rounded-l-lg border ml-0 shadow-md" name="search" id="" placeholder="search here" required>
            <button type="submit" class="px-3 py-2 text-gray-700 hover:shadow-lg hover:ring-2 hover:ring-offset-2 hover:ring-indigo-300 rounded-r-lg border ml-0 shadow-md">
                <?php echo $t->_('Search Product'); ?>
            </button>
        </form>
    </div>
    <div class="w-1/2 flex items-center">
        <button class="mr-2 px-3 py-2 text-gray-700 hover:shadow-lg hover:ring-2 hover:ring-offset-2 hover:ring-indigo-300 rounded-lg border ml-0 m-2 shadow-md">
            <?php echo $t->_('Add Product'); ?>
        </button>
        <?php
        if (isset($search)) {
        ?>
            <div class="px-1 h-6 text-sm text-gray-600 flex justify-center items-center shadow rounded-full border"><?php echo $query ?> <a href="/admin/products">
                    <ion-icon class="text-2xl text-indigo-600 drop-shadow-lg" name="close-circle"></ion-icon>
                </a></div>
        <?php
        }
        ?>
    </div>
    <table class="shadow-lg">
        <thead class="text-neutral-800 shadow-md">
            <th class="p-3 border"><?php echo $t->_('Product Name'); ?></th>
            <th class="p-3 border "><?php echo $t->_('Product Category'); ?></th>
            <th class="p-3 border "><?php echo $t->_('Product Price'); ?></th>
            <th class="p-3 border "><?php echo $t->_('Product Stock'); ?></th>
            <th class="p-3 border "><?php echo $t->_('View Product'); ?></th>
            <th class="p-3 border "><?php echo $t->_('Quick View'); ?></th>
            <th class="p-3 border "><?php echo $t->_('Edit Product'); ?></th>
            <th class="p-3 border "><?php echo $t->_('Delete Product'); ?></th>
        </thead>
        <tbody class="text-gray-700">
            <?php
            if (!isset($search)) {

                foreach ($data as $doc) {
            ?>
                    <tr class="cursor-pointer odd:bg-white even:bg-gray-100">
                        <td class="p-3 border"><?php echo $doc["product name"] ?></td>
                        <td class="p-3 border"><?php echo $doc["category name"] ?></td>
                        <td class="p-3 border"><?php echo $doc["product price"] ?></td>
                        <td class="p-3 border"><?php echo $doc["product stock"] ?></td>
                        <td class="p-3 border"><a class="text-indigo-500 underline italic" href="/products/details/<?php echo $doc["_id"] ?>">View Product</a></td>
                        <td class="p-3 border modaal-open italic text-pink-500 underline" data="<?php echo $doc["_id"] ?>">Quick view</td>
                        <td class="p-3 border"><a class="text-indigo-500 underline italic" href="/admin/products/edit/<?php echo $doc["_id"] ?>">Edit Product</a></td>
                        <td class="p-3 border"><a class="text-red-500 underline italic" href="/admin/products/delete/<?php echo $doc["_id"] ?>">Delete Product</a></td>
                    </tr>
                <?php
                }
            } else {
                foreach ($search as $doc) {
                ?>
                    <tr class="cursor-pointer odd:bg-white even:bg-gray-100">
                        <td class="p-3 border"><?php echo $doc["product name"] ?></td>
                        <td class="p-3 border"><?php echo $doc["category name"] ?></td>
                        <td class="p-3 border"><?php echo $doc["product price"] ?></td>
                        <td class="p-3 border"><?php echo $doc["product stock"] ?></td>
                        <td class="p-3 border"><a class="text-indigo-500 underline italic" href="/products/details/<?php echo $doc["_id"] ?>">View Product</a></td>
                        <td class="p-3 border modaal-open italic text-pink-500 underline" data="<?php echo $doc["_id"] ?>">Quick view</td>
                        <td class="p-3 border"><a class="text-indigo-500 underline italic" href="/products/edit/<?php echo $doc["_id"] ?>">Edit Product</a></td>
                        <td class="p-3 border"><a class="text-red-500 underline italic" href="/products/delete/<?php echo $doc["_id"] ?>">Delete Product</a></td>
                    </tr>
            <?php
                }
            }
            ?>
        </tbody>
    </table>
</div>
<div class="backdrop modaal hidden w-screen h-screen flex justify-center items-center p-3 bg-gray-700/25 fixed top-0 ">
    <div class="modaal-close w-full h-full bg-white p-3 rounded-lg border shadow-xl">
        <div class="top w-full text-right">
            <ion-icon name="close-circle" class="modaal-close text-2xl text-gray-700 hover:text-gray-900 cursor-pointer"></ion-icon>
        </div>
        <iframe class="w-full h-full product_url" src="http://localhost:8080/products/details/62594a58d34bb94c3207f022" title="product desc"></iframe>
    </div>
</div>
<?php
$this->assets->OutputJs();
?>